import type { Metadata } from "next";
import { Geist, Geist_Mono, Comforter} from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";

const comforter = Comforter({
  variable: "--font-comforter",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comforter.variable} antialiased`}
      >

        <AntdRegistry> {children}</AntdRegistry>
      </body>
    </html>
  );
}
