import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  anther,
  team
}: Readonly<{
  children: React.ReactNode;
  anther: React.ReactNode;
  team: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AntdRegistry> 
          <div className="flex justify-center gap-6">
              <Link href='/'>home</Link>
              <Link href='/visitors'>visitors</Link>
          </div>
          <div className="flex justify-center gap-6">
            {team}
            {anther}
          </div>
          {children}
        
          </AntdRegistry>
      </body>
    </html>
  );
}
